### ISSUE TITLE
CUDA FINUFFT slows down when repeatedly called 

### ISSUE THREAD

**Issue by maartenterpstra** [flatironinstitute/pytorch-finufft#105] opened 2024-04-03 10:08 UTC
Hi, 

Thanks for developing FINUFFT and corresponding Pytorch bindings. I'm running into an issue when repeatedly calling FINUFFT in the same context, an incremental slowdown is observed. This behaviour only occurs when FINUFFT is called on GPU devices. 

## Relevant information:
- Python: 3.11.8
- Pytorch: 2.2.2
- CUDA: 11.8
- (cu)FINUFFT: 2.2.0 (manually compiled from GIT)
- Numpy: 1.26.4

## Code to reproduce the issue:
```python
import numpy as np
import pytorch_finufft
import time
import torch
from tqdm.auto import tqdm
import matplotlib.pyplot as plt

np.random.seed(42)

def test_finufft_repeated(x, y, shape, device, ax, n_iters=100):
    points = torch.from_numpy(np.stack((x,y))).to(device)
    values = torch.ones(points.shape[1], dtype=torch.complex128).to(device)

    timings = []
    
    # Issue also occurs with (potential) gradient computation
    with torch.no_grad():
        for i in tqdm(range(n_iters)):
            torch.cuda.synchronize()

            t0 = time.time()
            # calculate the transform
            f = pytorch_finufft.functional.finufft_type1(points, values, shape)
            # synchronize for accurate timing. Irrelevant for the issue
            # as it also occurs without synchronization
            torch.cuda.synchronize()
            timings.append((time.time()-t0)*1000)
        
    print(device.upper())
    print(f"FINUFFT Timing: {np.mean(timings):.3f}±{np.std(timings):.3f} ms")
    
    xrange = np.arange(n_iters)
    a, b = np.polyfit(xrange, timings, deg=1)
    print(f"Trend: y={a:.3f}x + {b:.3f}")
    ax.plot(timings)
    ax.plot(a * xrange + b)
    ax.set_ylabel('Time (ms)')
    ax.set_xlabel('# iteration')
    ax.set_title(device.upper())
    ax.legend(["FINUFFT timing", f"Linear trend (y={a:.3f}x + {b:.3f})"])
    print("")
    
# the nonuniform points in the square [0,2pi)^2
M = 100000
x = 2 * np.pi * np.random.uniform(size=M)
y = 2 * np.pi * np.random.uniform(size=M)

n_iters = 10_000
f, ax = plt.subplots(1, 2, figsize=(10,5))

test_finufft_repeated(x, y, (128, 128), 'cpu', ax=ax[0], n_iters=n_iters)
test_finufft_repeated(x, y, (128, 128), 'cuda', ax=ax[1], n_iters=n_iters)
plt.tight_layout()
```

## Results
![afbeelding](https://github.com/flatironinstitute/pytorch-finufft/assets/43781235/f091480b-30b1-446b-b9b4-8a3b56f396e7)

### Additional information
- The presented code uses the Type1 NUFFT, but the issue is also present when using the Type2 NUFFT
- CUDA memory consumption also increases from ~850MiB after the first iteration to ~1150MiB for this particular example

**Comment by WardBrian** [comment] 2024-04-03 13:42
Thank you for what is one of the most thorough bug reports I have ever seen!

This sounds similar to #99. 

Unfortunately, my attempt to run your code was not able to re-create this trend: 

![plot-mem-time](https://github.com/flatironinstitute/pytorch-finufft/assets/31640292/5f695626-b8da-44c4-933a-8ef6189e588f)

My versions did differ slightly, I'm going to see if I can more closely re-create your environment next:

Python 3.10.10
Pytorch 2.0.1
CUDA Version: 12.2 
(cu)FINUFFT: 2.2.0 (also manually compiled)
Numpy: 1.23.5

**Comment by WardBrian** [comment] 2024-04-03 14:17
Python 3.11.2
Torch 2.2.2+cu118
CUDA 11.8
cuFINUFFT 2.2, just re-compiled
Numpy 1.26.4

![plot-mem-time](https://github.com/flatironinstitute/pytorch-finufft/assets/31640292/22b79338-164b-4076-a74e-cac495eefe08)


Unfortunately even with a closer environment I am not seeing the same trend. Possibly due to hardware? This is being done on a machine with a single `Tesla V100-SXM2-32GB`

**Comment by maartenterpstra** [comment] 2024-04-03 15:34
Hi Brian,

Thank you so much for investigating this issue. Very interesting that the results diverge so much. The original figure I posted was obtained on a NVIDIA RTX A5000-24GB. Based on your results, we did some more runs on different machines. 

## Machine A
(Tesla V100-32GB, cuda 11.2, python 3.11.8, torch 2.2.1, finufft 2.2.0)
![MicrosoftTeams-image](https://github.com/flatironinstitute/pytorch-finufft/assets/43781235/1f5ced08-dc3e-46d4-8b37-74f1760d4ddc)

## Machine B
(NVIDIA Quadro P6000, cuda 12.1, python 3.8.18, torch 2.1.1, finufft 2.2.0)
![MicrosoftTeams-image](https://github.com/flatironinstitute/pytorch-finufft/assets/43781235/0cf4e3db-dc80-4a15-9f7c-40afe1f6e67b)

This is quite puzzling as there does not seem to be a singular condition that triggers this behaviour. I have also tried to apply the PyTorch profiler to this issue, but it provides no further reporting other than that the time for `FinufftType1.apply` is increasing with each iterations. I'm kind of puzzled how to further investigate this issue.

**Comment by WardBrian** [comment] 2024-04-03 15:38
I suspect this plot is the reason:

![plot-pytorch-finufft](https://github.com/flatironinstitute/pytorch-finufft/assets/31640292/ab759397-9e2d-427d-8192-28015d22c2b9)


There does seem to be a memory leak (as reported in #99), but it doesn't seem to be one that pytorch can detect (e.g. `torch.cuda.memory_allocated()` is constant, but `nvidia-smi` is not).

I'm guessing that either driver versions or hardware differences mean that the V100 doesn't seem to care as much about the growing memory usage, but other GPUs might?

I'm currently investigating if this leak is caused by our package or something which afflicts the underlying cufinufft package

**Comment by WardBrian** [comment] 2024-04-03 16:02
I adapted your example to one that didn't use pytorch-finufft at all, just cufinufft, and found the same memory behavior. 

My guess is you would see the same slowdown on affected machines if you did a similar translation (`f = cufinufft.nufft2d1(*points, values, shape)`). I've opened an issue against the underlying package

**Comment by WardBrian** [comment] 2024-04-03 19:43
@maartenterpstra - are you able to use cuda 12? If so, do you see the same behaviors?

**Comment by maartenterpstra** [comment] 2024-04-04 12:29
Hi Brian,

Great that there seems to be a root cause 👍 ! Interesting that you were not able to reproduce this issue in your closely-matched environment then, but this might be also be a machine/graphics driver issue. 

Unfortunately, I am not in charge of the installed CUDA version on the machines on which we discovered the issue. I might be able to reproduce this on my personal machine but will not be able to do so until the end of April. Perhaps my collegue could investigate this issue in the meantime (He is also a pytorch-finufft user).

**Comment by thomasediolausson** [comment] 2024-04-08 16:36
Hi Brian,

Sorry for the delay. Thank you for all the detective work.

Indeed, this does not seem to be an issue when using cuda 12.1. 

I re-ran the test script on Machine B:
**cuda 11.8**
![image](https://github.com/flatironinstitute/pytorch-finufft/assets/90185739/2d4550a9-ae18-4e40-95bf-0c87b56778c6)

**cuda 12.1**
![image](https://github.com/flatironinstitute/pytorch-finufft/assets/90185739/72216f86-dd8d-49fc-8392-236893e9fbb8)


**Error in previous comment**
In the previous [comment](https://github.com/flatironinstitute/pytorch-finufft/issues/105#issuecomment-2034942224), a mistake was recorded in this test: Machine B was actually using **cuda 11.8**.

**Comment by WardBrian** [comment] 2024-04-08 21:08
Thanks for confirming! Since this is a CUDA bug I'm going to close this, but it is probably worth us adding a note to our documentation about it.

**Closed by WardBrian** 2024-04-08 21:08 UTC
